language:  python
services:
    - docker
pyton:
    - "2.7"
install:
    - make deps
script:
    - make lint
    - make test
after_success:
    - make docker_build
deploy:
  provider: heroku
  app: whispering-mountain-90714
  api_key: ${HEROKU_API_KEY}
